# Generated by Django 4.2.16 on 2024-12-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportdata',
            name='ACMARK',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='ACTYPE',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='CARRIER',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='Cockpit_to_Main_Gear_f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='FLIGHT',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='Main_Gear_Width_ft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='Month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='OneStep_Fluid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='TwoStep_II_Fluid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='TwoStep_I_Fluid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='Wingspan_ft_with_winglets_sharklets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='Wingspan_ft_without_winglets_sharklets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='Year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='deicing_time_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportdata',
            name='meteo_numerical',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
