# Generated by Django 4.2.16 on 2024-12-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airportdata_acmark_airportdata_actype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportdata',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='airportdata',
            name='std',
            field=models.CharField(max_length=50),
        ),
    ]
