# Generated by Django 4.2.16 on 2024-12-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_airportdata_date_alter_airportdata_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportdata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='airportdata',
            name='std',
            field=models.TimeField(),
        ),
    ]
