# Generated by Django 4.2.16 on 2024-12-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_airportdata_date_alter_airportdata_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportdata',
            name='std',
            field=models.FloatField(),
        ),
    ]
