# Generated by Django 4.2.16 on 2024-12-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_airportdata_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airportdata',
            old_name='Cockpit_to_Main_Gear_f',
            new_name='Cockpit_to_Main_Gear_ft',
        ),
    ]
